---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# treemixTools

<!-- badges: start -->
<!-- badges: end -->

The goal of treemixTools is to ...

## Installation

You can install the development version of treemixTools from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("thehung92/treemixTools")
```

## Example

This code load the treemix result from the package external data. Now my library can be load with a single `library` function call

```{r}
library(treemixTools)
#
infiles <- system.file('extdata', package='treemixTools') |> list.files(full.names=TRUE)
inStem <- infiles[1] |> gsub(pattern=".cov.gz", replacement="")
obj <- read_treemixResult(inStem)
str(obj)
```

## plot the graph with ggtree

```{r graph, fig.height=3, fig.width=6}
plot_treemix_graph(obj)
```

## plot the drift params heatmap

```{r drift, fig.height=3, fig.width=6}
plot_treemix_drift(obj)
```

## plot the residual heatmap 

```{r residual, fig.height=3, fig.width=6}
plot_treemix_residual(obj)
```

## merge
